name: Deploy to K3ss

on:
  push:
    branches:
      - master   # change to 'master' if your branch is master
  workflow_dispatch:  # allows manual run from Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Pull latest code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup Node.js to build React app
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. Install React dependencies & build app
    - name: Install dependencies and build React app
      run: |
        npm ci
        npm run build

    # 4. Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mysite:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/mysite:latest

    # 6. SSH into Azure VM & update K3s deployment
    - name: Deploy to K3s via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.K3S_SERVER_IP }}
        username: ${{ secrets.K3S_SERVER_USER }}
        key: ${{ secrets.K3S_SSH_KEY }}
        script: |
          kubectl set image deployment/mysite mysite=${{ secrets.DOCKER_USERNAME }}/mysite:latest --record
          kubectl rollout status deployment/mysite
