name: Deploy to K3s N

on:
  push:
    branches:
      - master  # run workflow only when pushing to main branch
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 1: Setup Node for React build
    - name:Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 2: Install deps & build React app
    - name: Install dependencies and build
      run: |
        npm ci
        npm run build

    # Step 3: Build & push Docker image
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mysite:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/mysite:latest

    # Step 4: Deploy to K3s via SSH
    - name: Deploy to K3s via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.K3S_SERVER_IP }}
        username: ${{ secrets.K3S_SERVER_USER }}
        key: ${{ secrets.K3S_SSH_KEY }}
        script: |
          kubectl set image deployment/mysite mysite=${{ secrets.DOCKER_USERNAME }}/mysite:latest --record
          kubectl rollout status deployment/mysite

